In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, f1_score

%matplotlib inline

In [8]:
data = pd.read_csv('/Users/jennihawk/Documents/Data Science/Classification/Churn Project/Models/chatr_clean.csv')

In [9]:
data.head()

customerID  SeniorCitizen  tenure  MonthlyCharges  TotalCharges  \
0  7590-VHVEG              0     1.0           29.85         29.85   
1  5575-GNVDE              0    34.0           56.95       1889.50   
2  3668-QPYBK              0     2.0           53.85        108.15   
3  7795-CFOCW              0    45.0           42.30       1840.75   
4  9237-HQITU              0     2.0           70.70        151.65   

   InternetService_Fiber  InternetService_No  Contract_One_Year  \
0                      0                   0                  0   
1                      0                   0                  1   
2                      0                   0                  0   
3                      0                   0                  1   
4                      1                   0                  0   

   Contract_Two_year  PaymentMethod_Crcard  ...  \
0                  0                     0  ...   
1                  0                     0  ...   
2                  0                     0  ...   
3                  0                     0  ...   
4                  0                     0  ...   

   DeviceProtection_No_internet_serv  DeviceProtection_Yes  \
0                                  0                     0   
1                                  0                     1   
2                                  0                     0   
3                                  0                     1   
4                                  0                     0   

   TechSupport_No_internet_serv  TechSupport_Yes  \
0                             0                0   
1                             0                0   
2                             0                0   
3                             0                1   
4                             0                0   

   StreamingTV_No_internet_serv  StreamingTV_Yes  \
0                             0                0   
1                             0                0   
2                             0                0   
3                             0                0   
4                             0                0   

   StreamingMovies_No_internet_serv  StreamingMovies_Yes  \
0                                 0                    0   
1                                 0                    0   
2                                 0                    0   
3                                 0                    0   
4                                 0                    0   

   PaperlessBilling_Yes  Churn_Yes  
0                     1          0  
1                     0          0  
2                     1          1  
3                     0          0  
4                     1          1  

[5 rows x 32 columns]

In [10]:
data.columns

Index(['customerID', 'SeniorCitizen', 'tenure', 'MonthlyCharges',
       'TotalCharges', 'InternetService_Fiber', 'InternetService_No',
       'Contract_One_Year', 'Contract_Two_year', 'PaymentMethod_Crcard',
       'PaymentMethod_Electr_Check', 'PaymentMethod_Mailed_check',
       'MultipleLines_No_phone_serv', 'MultipleLines_Yes', 'Dependents_Yes',
       'gender_Male', 'Partner_Yes', 'PhoneService_Yes',
       'OnlineSecurity_No_internet_serv', 'OnlineSecurity_Yes',
       'OnlineBackup_No_Internet_Serv', 'OnlineBackup_Yes',
       'DeviceProtection_No_internet_serv', 'DeviceProtection_Yes',
       'TechSupport_No_internet_serv', 'TechSupport_Yes',
       'StreamingTV_No_internet_serv', 'StreamingTV_Yes',
       'StreamingMovies_No_internet_serv', 'StreamingMovies_Yes',
       'PaperlessBilling_Yes', 'Churn_Yes'],
      dtype='object')

In [12]:
features_in = ['SeniorCitizen', 'tenure', 'MonthlyCharges',
       'TotalCharges', 'InternetService_Fiber', 'InternetService_No',
       'Contract_One_Year', 'Contract_Two_year', 'PaymentMethod_Crcard',
       'PaymentMethod_Electr_Check', 'PaymentMethod_Mailed_check',
       'MultipleLines_No_phone_serv', 'MultipleLines_Yes', 'Dependents_Yes',
       'gender_Male', 'Partner_Yes', 'PhoneService_Yes',
       'OnlineSecurity_No_internet_serv', 'OnlineSecurity_Yes',
       'OnlineBackup_No_Internet_Serv', 'OnlineBackup_Yes',
       'DeviceProtection_No_internet_serv', 'DeviceProtection_Yes',
       'TechSupport_No_internet_serv', 'TechSupport_Yes',
       'StreamingTV_No_internet_serv', 'StreamingTV_Yes',
       'StreamingMovies_No_internet_serv', 'StreamingMovies_Yes',
       'PaperlessBilling_Yes']

Y = data['Churn_Yes']
X = data[features_in]

X_train, X_test, y_train, y_test = train_test_split(X, Y, 
                                       test_size=.2,     
                                       random_state=42)

# Initialize Model
logreg = LogisticRegression()

In [14]:
# print(X_train.shape)
# print(X_test.shape)
# print(y_train.shape)
# print(y_test.shape)

#### Fit model to training data

In [16]:
logreg.fit(X_train,y_train)

/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

### See how our training data is doing

##### Average Rate of Churn on Test Data

In [18]:
np.mean(y_train)

0.2657777777777778

#### Hard Class Predictions

In [20]:
logreg.predict(X_train)[:5]

array([0, 0, 0, 0, 0])

#### Soft Class Predictions

In [21]:
logreg.predict_proba(X_train)[:5]

array([[0.74644153, 0.25355847],
       [0.60867882, 0.39132118],
       [0.72721018, 0.27278982],
       [0.98767672, 0.01232328],
       [0.87726794, 0.12273206]])

### Accuracy

In [22]:
logreg.score(X_train, y_train)

0.8085333333333333

### Confusion Matrix

In [28]:
# y_pred = logreg.predict(y_train)
# confusion_matrix(y, y_pred)

### Interpreting Coefficients

In [29]:
logreg.coef_, logreg.intercept_

(array([[ 3.44408053e-01, -6.40050673e-02,  6.28407234e-03,
          3.10487948e-04,  5.74514710e-01, -1.09045696e-01,
         -4.99388846e-01, -6.18903194e-01, -1.64692006e-01,
          1.81133903e-01, -6.88462670e-02,  2.54441212e-01,
          2.07028177e-01, -2.32593236e-01, -2.15372536e-02,
          9.53622653e-02, -4.49962329e-01, -1.09045696e-01,
         -6.06685847e-01, -1.09045696e-01, -1.82235002e-01,
         -1.09045696e-01, -7.47679871e-02, -1.09045696e-01,
         -6.07603508e-01, -1.09045696e-01,  1.90317885e-01,
         -1.09045696e-01,  2.15967538e-01,  3.31699276e-01]]),
 array([-0.1980317]))